training:
  batch_size: 256 # 1000
  n_epochs: 500
  n_iters: 1000001
  snapshot_freq: 10
  snapshot_sampling: true
  # discrete: true
  discrete: true
  alpha: 0.01


test:
  begin_ckpt: 5000
  end_ckpt: 300000                     
  batch_size: 128

data:
  n_classes: 5
  dataset: "PinWheel"
  samplesize: 10_000
  test_samplesize: 1_000
  size: 2
  num_workers: 0
  dtype: torch.float32
  logit_transform: true

sample:
  n_gen: 5000

model:
  path: 'ot'
  nllk: true
  v: 0.1
  ngf: 200 # 200 # 100 # 512
  fixz: true
  freqs: 2

optim:
  weight_decay: 0.0001
  lr: 0.0001 # 0.001 # try to use even smaller step size for the coupled ODE system
  multiplier: .8 # 1. larger is more concentrated?
  clip_value: 1.
  eps: 0.00000001

flow:
  k_dim: 5 # use even number for flow model
  z_dim: 1
  n_comp: 5
  freqs: 2
  ngf: 200 # 200 # 100 # 512 # should be the same as model ngf, otherwise easily goes off to infinity
  sig_min: .00001
  mul: .001 # this is to decrease the impact of div estimate on the ODE solver - make it faster by scaling it down
  tau: 1.
  beta: 1. # higher promotes uniformity
  fix_z: true
  fix_pi: true #false
